# Generated by Django 3.1.1 on 2021-05-20 05:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=100)),
                ('quiz_quest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quizname')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('quiz_quest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quiz_question')),
                ('quiz_quizname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizapp.quizname')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
