# Generated by Django 3.1.1 on 2021-05-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20210520_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz_answer',
        ),
    ]
